---
- hosts: localhost
  tasks:
  - name: add kub repsitory
    yum_repository:
      name: Kubernetes
      description: Kubernetes repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: install kubectl
    yum:
      name: kubectl
      state: present
      update_cache: yes
      test
      IuxmGCJoLlbJVc8Gr8oBx7Ct
